### ISSUE TITLE
Adding cluster jewel to tree causes error

### ISSUE THREAD

**Issue by Werneq** [atty303/pob-web#2]
![image](https://github.com/atty303/pob-web/assets/47800790/95b40891-f7d5-477d-b6f0-8e175e25f71d)

Steps:
1- Open a new tree
2- Allocate any cluster jewel slot
3- On Itens, search for a cluster jewel unique (you have to search by hand, since we can't type anything yet, voices will cause the bug)
4- Put on the slot selected in step 2.

**Comment by atty303** [comment]
Fixed in 0.2.0.
